-- =====================================================================
-- 10seed-batches.sql — sample upcoming batches (dates are relative to today)
-- GENERATED by `npm run seed:sql` from supabase/seed-data/seed-content.ts. Do not edit by hand.
-- Safe to re-run: existing rows are left untouched.
-- =====================================================================

-- agentic-ai (hybrid), starts in 14 days
insert into public.batches (course_id, start_date, mode, schedule, seats, status)
select c.id, current_date + 14, r.mode, r.schedule, r.seats, 'open'
from public.courses c
cross join jsonb_populate_record(null::public.batches, convert_from(decode('eyJtb2RlIjoiaHlicmlkIiwic2NoZWR1bGUiOiJTdW4g4oCTIFRodSwgNzowMCDigJMgODozMCBBTSIsInNlYXRzIjoyMH0=', 'base64'), 'UTF8')::jsonb) r
where c.slug = 'agentic-ai'
  and not exists (select 1 from public.batches x where x.course_id = c.id);

-- generative-ai (online), starts in 10 days
insert into public.batches (course_id, start_date, mode, schedule, seats, status)
select c.id, current_date + 10, r.mode, r.schedule, r.seats, 'open'
from public.courses c
cross join jsonb_populate_record(null::public.batches, convert_from(decode('eyJtb2RlIjoib25saW5lIiwic2NoZWR1bGUiOiJTdW4g4oCTIFRodSwgNjozMCDigJMgODowMCBQTSIsInNlYXRzIjoyNX0=', 'base64'), 'UTF8')::jsonb) r
where c.slug = 'generative-ai'
  and not exists (select 1 from public.batches x where x.course_id = c.id);

-- data-analytics (physical), starts in 7 days
insert into public.batches (course_id, start_date, mode, schedule, seats, status)
select c.id, current_date + 7, r.mode, r.schedule, r.seats, 'open'
from public.courses c
cross join jsonb_populate_record(null::public.batches, convert_from(decode('eyJtb2RlIjoicGh5c2ljYWwiLCJzY2hlZHVsZSI6IlN1biDigJMgRnJpLCAxMDowMCDigJMgMTE6MzAgQU0iLCJzZWF0cyI6MTh9', 'base64'), 'UTF8')::jsonb) r
where c.slug = 'data-analytics'
  and not exists (select 1 from public.batches x where x.course_id = c.id);

-- mern-stack-development (hybrid), starts in 12 days
insert into public.batches (course_id, start_date, mode, schedule, seats, status)
select c.id, current_date + 12, r.mode, r.schedule, r.seats, 'open'
from public.courses c
cross join jsonb_populate_record(null::public.batches, convert_from(decode('eyJtb2RlIjoiaHlicmlkIiwic2NoZWR1bGUiOiJTdW4g4oCTIFRodSwgNDowMCDigJMgNTozMCBQTSIsInNlYXRzIjoyMH0=', 'base64'), 'UTF8')::jsonb) r
where c.slug = 'mern-stack-development'
  and not exists (select 1 from public.batches x where x.course_id = c.id);

-- python (online), starts in 5 days
insert into public.batches (course_id, start_date, mode, schedule, seats, status)
select c.id, current_date + 5, r.mode, r.schedule, r.seats, 'open'
from public.courses c
cross join jsonb_populate_record(null::public.batches, convert_from(decode('eyJtb2RlIjoib25saW5lIiwic2NoZWR1bGUiOiJTdW4g4oCTIEZyaSwgNzowMCDigJMgODowMCBQTSIsInNlYXRzIjozMH0=', 'base64'), 'UTF8')::jsonb) r
where c.slug = 'python'
  and not exists (select 1 from public.batches x where x.course_id = c.id);

-- ui-ux-designing (physical), starts in 21 days
insert into public.batches (course_id, start_date, mode, schedule, seats, status)
select c.id, current_date + 21, r.mode, r.schedule, r.seats, 'open'
from public.courses c
cross join jsonb_populate_record(null::public.batches, convert_from(decode('eyJtb2RlIjoicGh5c2ljYWwiLCJzY2hlZHVsZSI6IlN1biDigJMgVGh1LCAxOjAwIOKAkyAyOjMwIFBNIiwic2VhdHMiOjE1fQ==', 'base64'), 'UTF8')::jsonb) r
where c.slug = 'ui-ux-designing'
  and not exists (select 1 from public.batches x where x.course_id = c.id);
