-- =====================================================================
-- 11seed-testimonials.sql — SAMPLE testimonials, seeded UNPUBLISHED. Replace with real reviews in Admin → Testimonials
-- GENERATED by `npm run seed:sql` from supabase/seed-data/seed-content.ts. Do not edit by hand.
-- Safe to re-run: existing rows are left untouched.
-- =====================================================================

-- Sample testimonial 1 (data-analytics)
insert into public.testimonials (name, role, organization, course_id, quote, rating, is_published, sort_order)
select r.name, r.role, r.organization, (select id from public.courses where slug = 'data-analytics'), r.quote, r.rating, false, r.sort_order
from jsonb_populate_record(null::public.testimonials, convert_from(decode('eyJuYW1lIjoiU2FtcGxlIExlYXJuZXIiLCJyb2xlIjoiRGF0YSBBbmFseXRpY3MgbGVhcm5lciIsIm9yZ2FuaXphdGlvbiI6bnVsbCwicXVvdGUiOiJUaGUgbWVudG9ycyBleHBsYWluZWQgZXZlcnkgY29uY2VwdCB3aXRoIHJlYWwgYnVzaW5lc3MgZGF0YS4gV2l0aGluIHdlZWtzIEkgd2FzIGJ1aWxkaW5nIFBvd2VyIEJJIGRhc2hib2FyZHMgZm9yIG15IG93biBvZmZpY2UgcmVwb3J0cy4iLCJyYXRpbmciOjUsInNvcnRfb3JkZXIiOjF9', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.testimonials x where x.quote = r.quote);

-- Sample testimonial 2 (mern-stack-development)
insert into public.testimonials (name, role, organization, course_id, quote, rating, is_published, sort_order)
select r.name, r.role, r.organization, (select id from public.courses where slug = 'mern-stack-development'), r.quote, r.rating, false, r.sort_order
from jsonb_populate_record(null::public.testimonials, convert_from(decode('eyJuYW1lIjoiU2FtcGxlIExlYXJuZXIiLCJyb2xlIjoiTUVSTiBTdGFjayBsZWFybmVyIiwib3JnYW5pemF0aW9uIjpudWxsLCJxdW90ZSI6IlRoZSByZWNvcmRlZCBjbGFzc2VzIGhlbHBlZCBtZSByZXZpc2UgYXQgbXkgb3duIHBhY2UsIGFuZCBidWlsZGluZyBhIGZ1bGwgZS1jb21tZXJjZSBwcm9qZWN0IGdhdmUgbWUgcmVhbCBjb25maWRlbmNlIGZvciBpbnRlcnZpZXdzLiIsInJhdGluZyI6NSwic29ydF9vcmRlciI6Mn0=', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.testimonials x where x.quote = r.quote);

-- Sample testimonial 3 (generative-ai)
insert into public.testimonials (name, role, organization, course_id, quote, rating, is_published, sort_order)
select r.name, r.role, r.organization, (select id from public.courses where slug = 'generative-ai'), r.quote, r.rating, false, r.sort_order
from jsonb_populate_record(null::public.testimonials, convert_from(decode('eyJuYW1lIjoiU2FtcGxlIExlYXJuZXIiLCJyb2xlIjoiR2VuZXJhdGl2ZSBBSSBsZWFybmVyIiwib3JnYW5pemF0aW9uIjpudWxsLCJxdW90ZSI6Ikkgam9pbmVkIGluIGh5YnJpZCBtb2RlLCBhdHRlbmRpbmcgdGhlIGxhYiBvbiB3ZWVrZW5kcyBhbmQgb25saW5lIG9uIHdlZWtkYXlzLiBTYW1lIGZlZSwgdG90YWwgZmxleGliaWxpdHksIGFuZCBhIGdyZWF0IHByb2plY3QgYXQgdGhlIGVuZC4iLCJyYXRpbmciOjUsInNvcnRfb3JkZXIiOjN9', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.testimonials x where x.quote = r.quote);

-- Sample testimonial 4 (ui-ux-designing)
insert into public.testimonials (name, role, organization, course_id, quote, rating, is_published, sort_order)
select r.name, r.role, r.organization, (select id from public.courses where slug = 'ui-ux-designing'), r.quote, r.rating, false, r.sort_order
from jsonb_populate_record(null::public.testimonials, convert_from(decode('eyJuYW1lIjoiU2FtcGxlIExlYXJuZXIiLCJyb2xlIjoiVUkvVVggRGVzaWduaW5nIGxlYXJuZXIiLCJvcmdhbml6YXRpb24iOm51bGwsInF1b3RlIjoiRnJvbSByZXNlYXJjaCB0byBwcm90b3R5cGVzIGluIEZpZ21hLCBldmVyeSBjbGFzcyB3YXMgaGFuZHMtb24uIEkgZmluaXNoZWQgd2l0aCB0d28gY2FzZSBzdHVkaWVzIGZvciBteSBwb3J0Zm9saW8uIiwicmF0aW5nIjo0LCJzb3J0X29yZGVyIjo0fQ==', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.testimonials x where x.quote = r.quote);
