-- =====================================================================
-- 4seed-settings.sql — site settings (contact details, hero text, stats)
-- GENERATED by `npm run seed:sql` from supabase/seed-data/seed-content.ts. Do not edit by hand.
-- Safe to re-run: existing rows are left untouched.
-- =====================================================================

insert into public.site_settings (id, site_name, tagline, announcement, hero_eyebrow, hero_title, hero_highlight, hero_subtitle, phone, whatsapp, email, address, office_hours, facebook_url, instagram_url, linkedin_url, tiktok_url, discord_url, stats)
values (1, 'Leafclutch Academy',
  'Learn by building. Grow by doing.',
  'New batches are open. Online, Hybrid and Physical classes all cost the same.',
  'Industry-led IT training in Nepal',
  'Build job-ready skills for',
  'the AI era',
  'Three-month, project-based programs in AI, data, development, security and design. Learn from working engineers, build real projects, and move into an internship.',
  '+977-9766715768',
  '9779766715768',
  'info@leafclutch.com.np',
  'Siddharthanagar, Rupandehi, Nepal',
  'Sun – Fri, 9:00 AM – 6:00 PM',
  'https://www.facebook.com/profile.php?id=61584902195796',
  'https://www.instagram.com/leafclutch.technologies',
  'https://www.linkedin.com/company/leafclutch-technologies',
  'https://www.tiktok.com/@leafclutchtechnologies',
  'https://discord.gg/4aDwcMZBPq',
  '[{"value":"12","label":"Career programs"},{"value":"3","label":"Learning modes, one fee"},{"value":"50%","label":"Fee to get started"},{"value":"100%","label":"Project-based learning"}]'::jsonb)
on conflict (id) do nothing;
