-- =====================================================================
-- 5seed-categories.sql — course categories
-- GENERATED by `npm run seed:sql` from supabase/seed-data/seed-content.ts. Do not edit by hand.
-- Safe to re-run: existing rows are left untouched.
-- =====================================================================

insert into public.categories (slug, name, description, icon, sort_order)
values ('ai-data', 'AI & Data', 'Agentic AI, generative AI, machine learning and data careers.', 'brain-circuit', 1)
on conflict (slug) do nothing;

insert into public.categories (slug, name, description, icon, sort_order)
values ('programming', 'Programming', 'Strong programming foundations with Python.', 'code', 2)
on conflict (slug) do nothing;

insert into public.categories (slug, name, description, icon, sort_order)
values ('web-development', 'Web Development', 'Frontend, backend and full-stack JavaScript.', 'layers', 3)
on conflict (slug) do nothing;

insert into public.categories (slug, name, description, icon, sort_order)
values ('cyber-security', 'Cyber Security', 'Ethical hacking and defensive security.', 'shield-check', 4)
on conflict (slug) do nothing;

insert into public.categories (slug, name, description, icon, sort_order)
values ('design', 'Design', 'UI/UX and graphic design with modern AI tools.', 'palette', 5)
on conflict (slug) do nothing;
