-- =====================================================================
-- 7seed-mentors.sql — mentors and the courses they teach
-- GENERATED by `npm run seed:sql` from supabase/seed-data/seed-content.ts. Do not edit by hand.
-- Safe to re-run: existing rows are left untouched.
-- =====================================================================

-- Rohan Aryal
insert into public.mentors (slug, name, role, bio, photo_url, expertise, linkedin_url, sort_order)
select r.slug, r.name, r.role, r.bio, r.photo_url, r.expertise, r.linkedin_url, r.sort_order
from jsonb_populate_record(null::public.mentors, convert_from(decode('eyJzbHVnIjoicm9oYW4tYXJ5YWwiLCJuYW1lIjoiUm9oYW4gQXJ5YWwiLCJyb2xlIjoiTWVudG9yIiwiYmlvIjoiUm9oYW4gbWVudG9ycyBMZWFmY2x1dGNoIEFjYWRlbXkncyBBSSBhbmQgZGF0YSBwcm9ncmFtcywgZ3VpZGluZyBsZWFybmVycyBmcm9tIHRoZWlyIGZpcnN0IGxpbmVzIG9mIFB5dGhvbiB0byBidWlsZGluZyBhZ2VudHMsIGdlbmVyYXRpdmUgQUkgYXBwbGljYXRpb25zLCBtYWNoaW5lIGxlYXJuaW5nIG1vZGVscyBhbmQgYW5hbHl0aWNzIGRhc2hib2FyZHMsIHdpdGggYSBzdHJvbmcgZm9jdXMgb24gaGFuZHMtb24gcHJvamVjdHMuIiwicGhvdG9fdXJsIjoiL21lbnRvcnMvcm9oYW4uanBlZyIsImV4cGVydGlzZSI6WyJBZ2VudGljIEFJIiwiR2VuZXJhdGl2ZSBBSSIsIkRhdGEgU2NpZW5jZSIsIkRhdGEgQW5hbHl0aWNzIiwiQUkvTUwiXSwibGlua2VkaW5fdXJsIjpudWxsLCJzb3J0X29yZGVyIjoxfQ==', 'base64'), 'UTF8')::jsonb) r
on conflict (slug) do nothing;

insert into public.course_mentors (course_id, mentor_id)
select c.id, m.id
from public.courses c
cross join public.mentors m
where m.slug = 'rohan-aryal'
  and c.slug in ('agentic-ai', 'generative-ai', 'data-science', 'data-analytics', 'ai-ml')
on conflict do nothing;
