-- =====================================================================
-- 8seed-faqs.sql — general FAQs shown on the home and contact pages
-- GENERATED by `npm run seed:sql` from supabase/seed-data/seed-content.ts. Do not edit by hand.
-- Safe to re-run: existing rows are left untouched.
-- =====================================================================

-- FAQ 1 (fees)
insert into public.faqs (question, answer, topic, sort_order)
select r.question, r.answer, r.topic, r.sort_order
from jsonb_populate_record(null::public.faqs, convert_from(decode('eyJxdWVzdGlvbiI6IkRvIE9ubGluZSwgSHlicmlkIGFuZCBQaHlzaWNhbCBjbGFzc2VzIGNvc3QgdGhlIHNhbWU/IiwiYW5zd2VyIjoiWWVzLiBFdmVyeSBwcm9ncmFtIGhhcyBvbmUgZmVlIHdoaWNoZXZlciBtb2RlIHlvdSBjaG9vc2UsIHNvIHlvdSBjYW4gcGljayB0aGUgZm9ybWF0IHRoYXQgc3VpdHMgeW91ciBzY2hlZHVsZSBhbmQgbG9jYXRpb24uIiwidG9waWMiOiJmZWVzIiwic29ydF9vcmRlciI6MX0=', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.faqs x where x.question = r.question);

-- FAQ 2 (fees)
insert into public.faqs (question, answer, topic, sort_order)
select r.question, r.answer, r.topic, r.sort_order
from jsonb_populate_record(null::public.faqs, convert_from(decode('eyJxdWVzdGlvbiI6IkhvdyBkb2VzIHRoZSBwYXltZW50IHBsYW4gd29yaz8iLCJhbnN3ZXIiOiJZb3UgcGF5IDUwJSBvZiB0aGUgZmVlIGF0IGVucm9sbG1lbnQgdG8gcmVzZXJ2ZSB5b3VyIHNlYXQgYW5kIHN0YXJ0IGxlYXJuaW5nLiBUaGUgcmVtYWluaW5nIDUwJSBpcyBwYWlkIHdoZW4geW91IGNvbXBsZXRlIHRoZSB0cmFpbmluZyBwaGFzZSBhbmQgYXJlIHByb21vdGVkIHRvIHRoZSBpbnRlcm5zaGlwLiIsInRvcGljIjoiZmVlcyIsInNvcnRfb3JkZXIiOjJ9', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.faqs x where x.question = r.question);

-- FAQ 3 (learning)
insert into public.faqs (question, answer, topic, sort_order)
select r.question, r.answer, r.topic, r.sort_order
from jsonb_populate_record(null::public.faqs, convert_from(decode('eyJxdWVzdGlvbiI6IldoYXQgaXMgdGhlIGRpZmZlcmVuY2UgYmV0d2VlbiBPbmxpbmUsIEh5YnJpZCBhbmQgUGh5c2ljYWwgY2xhc3Nlcz8iLCJhbnN3ZXIiOiJPbmxpbmUgY2xhc3NlcyBhcmUgbGl2ZSBhbmQgaW50ZXJhY3RpdmUgb3ZlciB2aWRlby4gUGh5c2ljYWwgY2xhc3NlcyBoYXBwZW4gaW4gcGVyc29uIGF0IG91ciBsYWIgaW4gU2lkZGhhcnRoYW5hZ2FyLiBIeWJyaWQgbGV0cyB5b3UgbWl4IGJvdGgsIGF0dGVuZGluZyBpbiBwZXJzb24gd2hlbiB5b3UgY2FuIGFuZCBqb2luaW5nIGxpdmUgb25saW5lIHdoZW4geW91IGNhbm5vdC4iLCJ0b3BpYyI6ImxlYXJuaW5nIiwic29ydF9vcmRlciI6M30=', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.faqs x where x.question = r.question);

-- FAQ 4 (learning)
insert into public.faqs (question, answer, topic, sort_order)
select r.question, r.answer, r.topic, r.sort_order
from jsonb_populate_record(null::public.faqs, convert_from(decode('eyJxdWVzdGlvbiI6IldpbGwgSSBnZXQgcmVjb3JkaW5ncyBvZiB0aGUgY2xhc3Nlcz8iLCJhbnN3ZXIiOiJZZXMuIEV2ZXJ5IGxpdmUgc2Vzc2lvbiBpcyByZWNvcmRlZCBhbmQgc2hhcmVkIHdpdGggeW91ciBiYXRjaCwgc28geW91IGNhbiByZXZpc2UgYW55IHRvcGljIG9yIGNhdGNoIHVwIG9uIGEgY2xhc3MgeW91IG1pc3NlZC4iLCJ0b3BpYyI6ImxlYXJuaW5nIiwic29ydF9vcmRlciI6NH0=', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.faqs x where x.question = r.question);

-- FAQ 5 (career)
insert into public.faqs (question, answer, topic, sort_order)
select r.question, r.answer, r.topic, r.sort_order
from jsonb_populate_record(null::public.faqs, convert_from(decode('eyJxdWVzdGlvbiI6IldoYXQgaXMgdGhlIGludGVybnNoaXAgcGF0aHdheT8iLCJhbnN3ZXIiOiJBZnRlciB0aGUgdGhyZWUtbW9udGggdHJhaW5pbmcsIHlvdXIgcHJvamVjdHMgYXJlIGV2YWx1YXRlZC4gTGVhcm5lcnMgd2hvIG1lZXQgdGhlIHN0YW5kYXJkIGFyZSBwcm9tb3RlZCB0byBhbiBpbnRlcm5zaGlwIHdoZXJlIHRoZXkgd29yayBvbiByZWFsIHByb2plY3RzIHdpdGggbWVudG9yIHN1cGVydmlzaW9uLiIsInRvcGljIjoiY2FyZWVyIiwic29ydF9vcmRlciI6NX0=', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.faqs x where x.question = r.question);

-- FAQ 6 (career)
insert into public.faqs (question, answer, topic, sort_order)
select r.question, r.answer, r.topic, r.sort_order
from jsonb_populate_record(null::public.faqs, convert_from(decode('eyJxdWVzdGlvbiI6IldpbGwgSSByZWNlaXZlIGEgY2VydGlmaWNhdGU/IiwiYW5zd2VyIjoiWWVzLiBZb3UgcmVjZWl2ZSBhIGNvbXBsZXRpb24gY2VydGlmaWNhdGUgd2l0aCBhIHVuaXF1ZSBjb2RlIHRoYXQgZW1wbG95ZXJzIGNhbiBjaGVjayBhdCB2ZXJpZnkubGVhZmNsdXRjaC5jb20ubnAuIiwidG9waWMiOiJjYXJlZXIiLCJzb3J0X29yZGVyIjo2fQ==', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.faqs x where x.question = r.question);

-- FAQ 7 (learning)
insert into public.faqs (question, answer, topic, sort_order)
select r.question, r.answer, r.topic, r.sort_order
from jsonb_populate_record(null::public.faqs, convert_from(decode('eyJxdWVzdGlvbiI6IldoYXQgZG8gSSBuZWVkIHRvIGpvaW4/IiwiYW5zd2VyIjoiQSBsYXB0b3AgYW5kIGEgc3RhYmxlIGludGVybmV0IGNvbm5lY3Rpb24gZm9yIG9ubGluZSBvciBoeWJyaWQgbGVhcm5pbmcuIEVhY2ggY291cnNlIHBhZ2UgbGlzdHMgYW55IHNwZWNpZmljIHJlcXVpcmVtZW50cy4iLCJ0b3BpYyI6ImxlYXJuaW5nIiwic29ydF9vcmRlciI6N30=', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.faqs x where x.question = r.question);

-- FAQ 8 (general)
insert into public.faqs (question, answer, topic, sort_order)
select r.question, r.answer, r.topic, r.sort_order
from jsonb_populate_record(null::public.faqs, convert_from(decode('eyJxdWVzdGlvbiI6IkRvIHlvdSBydW4gcHJvZ3JhbXMgZm9yIHNjaG9vbHMsIGNvbGxlZ2VzIGFuZCBjb21wYW5pZXM/IiwiYW5zd2VyIjoiWWVzLiBXZSBydW4gY29ycG9yYXRlIHVwc2tpbGxpbmcsIHNjaG9vbCBhbmQgY29sbGVnZSBjYW1wYWlnbnMsIGJvb3RjYW1wcyBhbmQgd29ya3Nob3BzLiBWaXNpdCB0aGUgQ29ycG9yYXRlICYgSW5zdGl0dXRpb25zIHBhZ2UgdG8gcmVxdWVzdCBhIHByb3Bvc2FsLiIsInRvcGljIjoiZ2VuZXJhbCIsInNvcnRfb3JkZXIiOjh9', 'base64'), 'UTF8')::jsonb) r
where not exists (select 1 from public.faqs x where x.question = r.question);
