-- =====================================================================
-- 9seed-programs.sql — corporate, school, college and institutional programs
-- GENERATED by `npm run seed:sql` from supabase/seed-data/seed-content.ts. Do not edit by hand.
-- Safe to re-run: existing rows are left untouched.
-- =====================================================================

-- Corporate Upskilling
insert into public.programs (slug, title, audience, duration, summary, highlights, icon, sort_order)
select r.slug, r.title, r.audience, r.duration, r.summary, r.highlights, r.icon, r.sort_order
from jsonb_populate_record(null::public.programs, convert_from(decode('eyJzbHVnIjoiY29ycG9yYXRlLXVwc2tpbGxpbmciLCJ0aXRsZSI6IkNvcnBvcmF0ZSBVcHNraWxsaW5nIiwiYXVkaWVuY2UiOiJjb3Jwb3JhdGUiLCJkdXJhdGlvbiI6IjEg4oCTIDggd2Vla3MiLCJzdW1tYXJ5IjoiQ3VzdG9taXNlZCB0cmFpbmluZyBmb3IgeW91ciB0ZWFtcyBpbiBBSSBhZG9wdGlvbiwgZGF0YSBhbmFseXRpY3MsIHNvZnR3YXJlIGRldmVsb3BtZW50IGFuZCBjeWJlciBzZWN1cml0eSBhd2FyZW5lc3MuIiwiaGlnaGxpZ2h0cyI6WyJDdXJyaWN1bHVtIHRhaWxvcmVkIHRvIHlvdXIgdG9vbHMgYW5kIGdvYWxzIiwiT24tc2l0ZSwgb25saW5lIG9yIGh5YnJpZCBkZWxpdmVyeSIsIkhhbmRzLW9uIHdvcmsgd2l0aCB5b3VyIHJlYWwgdXNlIGNhc2VzIiwiUHJvZ3Jlc3MgcmVwb3J0cyBmb3IgbWFuYWdlcnMiXSwiaWNvbiI6ImJyaWVmY2FzZSIsInNvcnRfb3JkZXIiOjF9', 'base64'), 'UTF8')::jsonb) r
on conflict (slug) do nothing;

-- School AI & Coding Campaign
insert into public.programs (slug, title, audience, duration, summary, highlights, icon, sort_order)
select r.slug, r.title, r.audience, r.duration, r.summary, r.highlights, r.icon, r.sort_order
from jsonb_populate_record(null::public.programs, convert_from(decode('eyJzbHVnIjoic2Nob29sLWFpLWNvZGluZy1jYW1wYWlnbiIsInRpdGxlIjoiU2Nob29sIEFJICYgQ29kaW5nIENhbXBhaWduIiwiYXVkaWVuY2UiOiJzY2hvb2wiLCJkdXJhdGlvbiI6IjEg4oCTIDQgd2Vla3MiLCJzdW1tYXJ5IjoiU2hvcnQsIGZ1biBhbmQgcHJhY3RpY2FsIGNhbXBhaWducyB0aGF0IGludHJvZHVjZSBzY2hvb2wgc3R1ZGVudHMgdG8gQUksIGNvZGluZywgZGVzaWduIGFuZCBzYWZlIGludGVybmV0IHVzZS4iLCJoaWdobGlnaHRzIjpbIkFnZS1hcHByb3ByaWF0ZSBjb250ZW50IGZvciBncmFkZXMgNiDigJMgMTIiLCJDb25kdWN0ZWQgYXQgeW91ciBzY2hvb2wgYnkgb3VyIG1lbnRvcnMiLCJNaW5pLXByb2plY3RzIGFuZCBzaG93Y2FzZSBkYXkiLCJDZXJ0aWZpY2F0ZXMgZm9yIGV2ZXJ5IHBhcnRpY2lwYW50Il0sImljb24iOiJzY2hvb2wiLCJzb3J0X29yZGVyIjoyfQ==', 'base64'), 'UTF8')::jsonb) r
on conflict (slug) do nothing;

-- College Bootcamps & Workshops
insert into public.programs (slug, title, audience, duration, summary, highlights, icon, sort_order)
select r.slug, r.title, r.audience, r.duration, r.summary, r.highlights, r.icon, r.sort_order
from jsonb_populate_record(null::public.programs, convert_from(decode('eyJzbHVnIjoiY29sbGVnZS1ib290Y2FtcHMiLCJ0aXRsZSI6IkNvbGxlZ2UgQm9vdGNhbXBzICYgV29ya3Nob3BzIiwiYXVkaWVuY2UiOiJjb2xsZWdlIiwiZHVyYXRpb24iOiIyIGRheXMg4oCTIDQgd2Vla3MiLCJzdW1tYXJ5IjoiSW50ZW5zaXZlIGJvb3RjYW1wcyBvbiBHZW5lcmF0aXZlIEFJLCBNRVJOLCBkYXRhIGFuYWx5dGljcyBhbmQgZXRoaWNhbCBoYWNraW5nIGZvciArMiBhbmQgYmFjaGVsb3Igc3R1ZGVudHMuIiwiaGlnaGxpZ2h0cyI6WyJJbmR1c3RyeS1yZWxldmFudCwgcHJvamVjdC1maXJzdCBzZXNzaW9ucyIsIlNjaGVkdWxlZCBhcm91bmQgeW91ciBhY2FkZW1pYyBjYWxlbmRhciIsIkhhY2thdGhvbnMgYW5kIHByb2plY3QgY29tcGV0aXRpb25zIiwiSW50ZXJuc2hpcCBwYXRod2F5IGZvciB0b3AgcGVyZm9ybWVycyJdLCJpY29uIjoiZ3JhZHVhdGlvbi1jYXAiLCJzb3J0X29yZGVyIjozfQ==', 'base64'), 'UTF8')::jsonb) r
on conflict (slug) do nothing;

-- Institutional Partnership
insert into public.programs (slug, title, audience, duration, summary, highlights, icon, sort_order)
select r.slug, r.title, r.audience, r.duration, r.summary, r.highlights, r.icon, r.sort_order
from jsonb_populate_record(null::public.programs, convert_from(decode('eyJzbHVnIjoiaW5zdGl0dXRpb25hbC1wYXJ0bmVyc2hpcCIsInRpdGxlIjoiSW5zdGl0dXRpb25hbCBQYXJ0bmVyc2hpcCIsImF1ZGllbmNlIjoiaW5zdGl0dXRpb24iLCJkdXJhdGlvbiI6IlNlbWVzdGVyIG9yIHllYXJseSIsInN1bW1hcnkiOiJSdW4gTGVhZmNsdXRjaCBBY2FkZW15IHByb2dyYW1zIGF0IHlvdXIgaW5zdGl0dXRlIHdpdGggb3VyIGN1cnJpY3VsdW0sIG1lbnRvciBzdXBwb3J0IGFuZCB0cmFpbi10aGUtdHJhaW5lciBzZXNzaW9ucy4iLCJoaWdobGlnaHRzIjpbIlJlYWR5LXRvLXRlYWNoIGN1cnJpY3VsdW0gYW5kIHByb2plY3RzIiwiVHJhaW4tdGhlLXRyYWluZXIgZm9yIHlvdXIgZmFjdWx0eSIsIkpvaW50IGNlcnRpZmljYXRlcyIsIk9uZ29pbmcgYWNhZGVtaWMgc3VwcG9ydCJdLCJpY29uIjoiYnVpbGRpbmctMiIsInNvcnRfb3JkZXIiOjR9', 'base64'), 'UTF8')::jsonb) r
on conflict (slug) do nothing;
