/**
 * Generates supabase/4seed-*.sql … supabase/11seed-*.sql from supabase/seed-data/seed-content.ts
 *
 *   npm run seed:sql
 *
 * Every generated statement is idempotent and never overwrites rows you have
 * already edited in the admin panel (ON CONFLICT DO NOTHING / NOT EXISTS guards).
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ALL_MODES,
  DEFAULT_DURATION,
  DEFAULT_INCLUDES,
  DEFAULT_INSTALLMENTS,
  seedBatches,
  seedCategories,
  seedCourses,
  seedFaqs,
  seedMentors,
  seedPrograms,
  seedSettings,
  seedTestimonials,
} from "./seed-content.ts";
import { curriculumOutlines } from "./curriculum-outlines.ts";
import { parseOutline } from "../../src/lib/curriculum.ts";

/** Detailed Lesson → Section → Points curriculum when an outline exists, else the short one. */
const curriculumFor = (slug: string, fallback: unknown) =>
  curriculumOutlines[slug] ? parseOutline(curriculumOutlines[slug]!) : fallback;

const b64 = (v: unknown) => Buffer.from(JSON.stringify(v), "utf8").toString("base64");

const outDir = join(dirname(fileURLToPath(import.meta.url)), "..");

const quote = (v: string) => `'${v.replace(/'/g, "''")}'`;
/**
 * Single-line SQL string literal. Line breaks become chr(10) so every value stays on one line:
 * the Supabase SQL Editor mis-reads string literals that span several lines.
 */
const str = (v: string | null | undefined) =>
  v == null ? "null" : v.includes("\n") ? `(${v.split("\n").map(quote).join(" || chr(10) || ")})` : quote(v);
const json = (v: unknown) => `${str(JSON.stringify(v))}::jsonb`;

function header(file: string, about: string, rerun = "Safe to re-run: existing rows are left untouched.") {
  return `-- =====================================================================
-- ${file} — ${about}
-- GENERATED by \`npm run seed:sql\` from supabase/seed-data/seed-content.ts. Do not edit by hand.
-- ${rerun}
-- =====================================================================

`;
}

/** The Supabase SQL Editor breaks on line breaks or semicolons inside string literals. */
function assertEditorSafe(file: string, sql: string) {
  let inString = false;
  let start = 0;
  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i];
    if (ch === "'") {
      if (inString && sql[i + 1] === "'") i++; // escaped quote
      else {
        inString = !inString;
        start = i;
      }
    } else if (inString && (ch === "\n" || ch === ";")) {
      throw new Error(`${file}: remove the ${ch === ";" ? "semicolon" : "line break"} from this text: ${sql.slice(start, start + 80)}`);
    }
  }
}

function write(file: string, about: string, body: string, rerun?: string) {
  assertEditorSafe(file, body);
  writeFileSync(join(outDir, file), header(file, about, rerun) + body.trim() + "\n");
  console.log("wrote", file);
}

// 4 — settings
{
  const s = seedSettings;
  // Only non-empty values, so this file never references columns added by later files
  const cols = (Object.keys(s) as (keyof typeof s)[]).filter((c) => s[c] !== null);
  const values = cols.map((c) => (c === "stats" ? json(s.stats) : str(s[c] as string | null)));
  write(
    "4seed-settings.sql",
    "site settings (contact details, hero text, stats)",
    `insert into public.site_settings (id, ${cols.join(", ")})
values (1, ${values.join(",\n  ")})
on conflict (id) do nothing;`,
  );
}

// 5 — categories
write(
  "5seed-categories.sql",
  "course categories",
  seedCategories
    .map(
      (c, i) => `insert into public.categories (slug, name, description, icon, sort_order)
values (${str(c.slug)}, ${str(c.name)}, ${str(c.description)}, ${str(c.icon)}, ${i + 1})
on conflict (slug) do nothing;`,
    )
    .join("\n\n"),
);

/* ------------------------------------------------------------------ */
/* Files 6–11 carry long free text (descriptions, curricula, FAQs).    */
/* Each record's content is shipped as one base64-encoded JSON value   */
/* and decoded by the database, so the SQL text itself contains no     */
/* prose, quotes, colons or line breaks for an editor to misread.      */
/* ------------------------------------------------------------------ */

/** `jsonb_populate_record(...) r` over a base64 JSON payload shaped like the table's row. */
function record(table: string, row: Record<string, unknown>) {
  const b64 = Buffer.from(JSON.stringify(row), "utf8").toString("base64");
  return `jsonb_populate_record(null::public.${table}, convert_from(decode('${b64}', 'base64'), 'UTF8')::jsonb) r`;
}

// 6 — courses
const COURSE_COLUMNS = [
  "slug", "title", "subtitle", "description", "fee", "duration", "level", "modes",
  "badge", "is_ai_integrated", "is_featured", "is_published", "sort_order", "icon", "accent",
  "tools", "outcomes", "prerequisites", "includes", "careers", "curriculum", "faqs", "installments",
];
write(
  "6seed-courses.sql",
  "the 12 programs with curriculum, tools, FAQs and payment plan",
  seedCourses
    .map((c, i) => {
      const row = {
        slug: c.slug,
        title: c.title,
        subtitle: c.subtitle,
        description: c.description,
        fee: c.fee,
        duration: DEFAULT_DURATION,
        level: c.level,
        modes: ALL_MODES,
        badge: c.badge,
        is_ai_integrated: c.is_ai_integrated,
        is_featured: c.is_featured,
        is_published: true,
        sort_order: i + 1,
        icon: c.icon,
        accent: c.accent,
        tools: c.tools,
        outcomes: c.outcomes,
        prerequisites: c.prerequisites,
        includes: DEFAULT_INCLUDES,
        careers: c.careers,
        curriculum: curriculumFor(c.slug, c.curriculum),
        faqs: c.faqs,
        installments: DEFAULT_INSTALLMENTS,
      };
      return `-- ${i + 1}. ${c.title} — NPR ${c.fee.toLocaleString("en-IN")}
insert into public.courses (category_id, ${COURSE_COLUMNS.join(", ")})
select (select id from public.categories where slug = ${str(c.category)}), ${COURSE_COLUMNS.map((k) => `r.${k}`).join(", ")}
from ${record("courses", row)}
on conflict (slug) do nothing;`;
    })
    .join("\n\n"),
);

// 7 — mentors + course links
write(
  "7seed-mentors.sql",
  "mentors and the courses they teach",
  seedMentors
    .map(
      (m, i) => `-- ${m.name}
insert into public.mentors (slug, name, role, bio, photo_url, expertise, linkedin_url, sort_order)
select r.slug, r.name, r.role, r.bio, r.photo_url, r.expertise, r.linkedin_url, r.sort_order
from ${record("mentors", { slug: m.slug, name: m.name, role: m.role, bio: m.bio, photo_url: m.photo_url, expertise: m.expertise, linkedin_url: m.linkedin_url, sort_order: i + 1 })}
on conflict (slug) do nothing;

insert into public.course_mentors (course_id, mentor_id)
select c.id, m.id
from public.courses c
cross join public.mentors m
where m.slug = ${str(m.slug)}
  and c.slug in (${m.courses.map(str).join(", ")})
on conflict do nothing;`,
    )
    .join("\n\n"),
);

// 8 — FAQs
write(
  "8seed-faqs.sql",
  "general FAQs shown on the home and contact pages",
  seedFaqs
    .map(
      (f, i) => `-- FAQ ${i + 1} (${f.topic})
insert into public.faqs (question, answer, topic, sort_order)
select r.question, r.answer, r.topic, r.sort_order
from ${record("faqs", { question: f.question, answer: f.answer, topic: f.topic, sort_order: i + 1 })}
where not exists (select 1 from public.faqs x where x.question = r.question);`,
    )
    .join("\n\n"),
);

// 9 — corporate & institutional programs
write(
  "9seed-programs.sql",
  "corporate, school, college and institutional programs",
  seedPrograms
    .map(
      (p, i) => `-- ${p.title}
insert into public.programs (slug, title, audience, duration, summary, highlights, icon, sort_order)
select r.slug, r.title, r.audience, r.duration, r.summary, r.highlights, r.icon, r.sort_order
from ${record("programs", { slug: p.slug, title: p.title, audience: p.audience, duration: p.duration, summary: p.summary, highlights: p.highlights, icon: p.icon, sort_order: i + 1 })}
on conflict (slug) do nothing;`,
    )
    .join("\n\n"),
);

// 10 — upcoming batches (dates relative to the day you run it)
write(
  "10seed-batches.sql",
  "sample upcoming batches (dates are relative to today)",
  seedBatches
    .map(
      (b) => `-- ${b.course} (${b.mode}), starts in ${b.startsInDays} days
insert into public.batches (course_id, start_date, mode, schedule, seats, status)
select c.id, current_date + ${b.startsInDays}, r.mode, r.schedule, r.seats, 'open'
from public.courses c
cross join ${record("batches", { mode: b.mode, schedule: b.schedule, seats: b.seats })}
where c.slug = ${str(b.course)}
  and not exists (select 1 from public.batches x where x.course_id = c.id);`,
    )
    .join("\n\n"),
);

// 11 — sample testimonials (unpublished)
write(
  "11seed-testimonials.sql",
  "SAMPLE testimonials, seeded UNPUBLISHED. Replace with real reviews in Admin → Testimonials",
  seedTestimonials
    .map(
      (t, i) => `-- Sample testimonial ${i + 1} (${t.course})
insert into public.testimonials (name, role, organization, course_id, quote, rating, is_published, sort_order)
select r.name, r.role, r.organization, (select id from public.courses where slug = ${str(t.course)}), r.quote, r.rating, false, r.sort_order
from ${record("testimonials", { name: t.name, role: t.role, organization: t.organization, quote: t.quote, rating: t.rating, sort_order: i + 1 })}
where not exists (select 1 from public.testimonials x where x.quote = r.quote);`,
    )
    .join("\n\n"),
);

// 13 — certificate image setting + detailed curricula for databases seeded earlier
write(
  "13certificate-and-detailed-curriculum.sql",
  "certificate sample image setting and detailed Lesson → Section → Points curricula",
  `-- Certificate sample image, uploaded in Admin → Site settings
alter table public.site_settings add column if not exists certificate_image_url text;

-- Detailed curricula. NOTE: this REPLACES the curriculum of these 12 courses.
-- Skip the updates below if you have already written your own curricula in the admin panel.

` +
    seedCourses
      .filter((c) => curriculumOutlines[c.slug])
      .map(
        (c) => `-- ${c.title}
update public.courses
set curriculum = convert_from(decode('${b64(curriculumFor(c.slug, c.curriculum))}', 'base64'), 'UTF8')::jsonb
where slug = ${str(c.slug)};`,
      )
      .join("\n\n"),
  "Safe to re-run. Replaces the curriculum of the 12 starter courses (see note below).",
);
